apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: calculator-prod

resources:
- ../../base

commonLabels:
  environment: production

patches:
- target:
    kind: Deployment
    name: calculator-app
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 5
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "256Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "200m"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "512Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "500m"

images:
- name: urielgarciarj/cicd-images
  newTag: calculator-prod-latest 