apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: calculator-dev

resources:
- ../../base

commonLabels:
  environment: development

patches:
- target:
    kind: Deployment
    name: calculator-app
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "64Mi"
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "50m"

images:
- name: urielgarciarj/cicd-images
  newTag: calculator-dev-latest 