name: Triggered Deployment

on:
  repository_dispatch:
    types: [image-built]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Update kube config
        run: aws eks update-kubeconfig --name calculator-eks-dev --region us-east-1
        
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
          
      - name: Install kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/
          
      - name: Update image tag
        run: |
          # Actualizar el tag de la imagen en el overlay de desarrollo
          sed -i "s/newTag: .*/newTag: ${{ github.event.client_payload.image_tag }}/" overlays/development/kustomization.yaml
          
      - name: Deploy to Kubernetes
        run: |
          # Aplicar los manifiestos usando kustomize para desarrollo
          kubectl apply -k overlays/development/
          
          # Esperar a que el deployment esté listo
          kubectl rollout status deployment/calculator-app -n calculator-dev --timeout=300s
          
      - name: Verify deployment
        run: |
          # Verificar que los pods estén corriendo
          kubectl get pods -n calculator-dev
          
          # Verificar que el servicio esté disponible
          kubectl get svc -n calculator-dev 